### ISSUE TITLE
Onboard @Calinou

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#17]
@Calinou Welcome! Any questions about Liberapay's source code or something else? You can ask them here. :-)

**Comment by Calinou** [comment]
I get this traceback when searching any term on my local installation of Liberapay (Fedora 23 64-bit):

```
Traceback (most recent call last):
  File "/home/hugo/Git/liberapay.com/env/lib/python2.7/site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "/home/hugo/Git/liberapay.com/env/lib/python2.7/site-packages/aspen/algorithms/website.py", line 162, in delegate_error_to_simplate
    response = resource.respond(state)
  File "/home/hugo/Git/liberapay.com/env/lib/python2.7/site-packages/aspen/http/resource.py", line 59, in respond
    content_type, body = super(Dynamic, self).respond(accept, state)
  File "/home/hugo/Git/liberapay.com/env/lib/python2.7/site-packages/aspen/simplates/__init__.py", line 180, in respond
    body = render(context)
  File "/home/hugo/Git/liberapay.com/env/lib/python2.7/site-packages/aspen/simplates/renderers/__init__.py", line 150, in __call__
    return self.render_content(context)
  File "/home/hugo/Git/liberapay.com/liberapay/renderers/jinja2_htmlescaped.py", line 17, in render_content
    return base.Renderer.render_content(self, context)
  File "/home/hugo/Git/liberapay.com/env/lib/python2.7/site-packages/aspen_jinja2_renderer.py", line 66, in render_content
    return self.compiled.render(context).encode(charset)
  File "/home/hugo/Git/liberapay.com/env/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hugo/Git/liberapay.com/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hugo/Git/liberapay.com/error.spt", line 4, in top-level template code
  File "/home/hugo/Git/liberapay.com/templates/base.html", line 77, in top-level template code
    {% block content %}{% endblock %}
  File "/home/hugo/Git/liberapay.com/error.spt", line 17, in block "content"
    if isinstance(response, LazyResponse):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1508: ordinal not in range(128)
```

**Comment by Changaco** [comment]
The first thing you need to know is that the line numbers in tracebacks are sometimes incorrect when the file is a `.spt`: https://github.com/liberapay/liberapay.com/issues/121 /o\

The failure is actually here: https://github.com/liberapay/liberapay.com/blob/58/error.spt#L40

**Comment by Changaco** [comment]
Here's how I reproduced the error:

```diff
diff --git a/www/search.spt b/www/search.spt
index 944b981..0b82c0d 100644
--- a/www/search.spt
+++ b/www/search.spt
@@ -1,3 +1,7 @@
+# coding: utf8
+
+from aspen import Response
+
 from liberapay.utils import markdown
 from liberapay.utils.i18n import LANGUAGES_2, SEARCH_CONFS, strip_accents
 
@@ -9,6 +13,8 @@ scope = request.qs.get('scope')
 title = _("Search")
 results = {}
 
+raise Response(400, b'é')
+
 if query:
     subhead = query
     q = strip_accents(query)
```

And here is the fix:

```diff
diff --git a/error.spt b/error.spt
index 932bb36..4b043a6 100644
--- a/error.spt
+++ b/error.spt
@@ -17,6 +17,8 @@ except Exception as e:
 if isinstance(response, LazyResponse):
     response.render_body(state)
 err = response.body
+if err and isinstance(err, bytes):
+    err = err.decode(response.charset)
 if code == 500 and not err:
     err = _("Looks like you've found a bug! Sorry for the inconvenience, we'll get it fixed ASAP!")
 
```

Let me know if it works for you.
